[project]
name = "mavic-helper"
version = "0.1.0"
description = "Add a short description here"
authors = ["mrahnis <mrahnis@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
matplotlib = ">=3.8.2,<3.9"
exifread = ">=3.0.0,<3.1"
numpy = ">=1.26.3,<1.27"
setuptools = ">=69.1.1,<69.2"
pip = ">=23.3.2,<23.4"
scipy = ">=1.12.0,<1.13"
defusedxml = ">=0.7.1,<0.8"
requests = ">=2.31.0,<2.32"
build = ">=0.7.0,<0.8"
fiona = ">=1.9.6,<1.10"
shapely = ">=2.0.3,<2.1"
pyproj = ">=3.6.1,<3.7"
rasterio = ">=1.3.9,<1.4"

[pypi-dependencies]
dji-thermal-sdk = "*"
pandas = "*"
